#  1: Introduction to NumPy (01_NumPy_Basics.ipynb)

## 1. What is NumPy? / Why NumPy?

### Concept Explanation
NumPy (Numerical Python) is a library for fast, efficient array/
numerical computation in Python. Unlike plain Python lists, NumPy 
arrays are stored in contiguous memory and operations run in 
optimized C code - making them much faster for large-scale math.

### Real-world Example
A weather station recording millions of temperature readings needs 
fast calculations (averages, trends) - plain Python loops would be 
too slow for this scale.

### Business Example
An e-commerce company processing millions of transaction records 
daily uses NumPy-based tools to calculate revenue statistics 
quickly, instead of slow manual looping.

### AI/ML Example
Every ML library (Pandas, Scikit-learn, TensorFlow) is built ON 
TOP of NumPy internally - it's the foundational layer for numerical 
computation in the entire Python AI/ML ecosystem.

In [3]:
# Step 3 – Implement the Concept
import numpy as np

# Comparing Python list vs NumPy array
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

# Vectorized operation (element-wise multiplication)
result = numpy_array * 2

print("Python List:", python_list)
print("NumPy Array Result:", result)

Python List: [1, 2, 3, 4, 5]
NumPy Array Result: [ 2  4  6  8 10]


## 2. NumPy Arrays (ndarray) and Creating Arrays

### Concept Explanation
The `ndarray` is NumPy's core data structure - an n-dimensional array. Arrays can be created from lists, or using built-in generators like `zeros`, `ones`, `arange`, `linspace`.

### Real-world Example
A grid of sensor readings across a city (rows = locations, columns = time) is naturally represented as a 2D `ndarray`.

### Business Example
A retail chain storing daily sales across multiple stores and products uses a multi-dimensional array structure (store × product × day) for efficient bulk analysis.

### AI/ML Example
Image data is stored as `ndarray`s - a color image is a 3D array (height × width × color channels), and NumPy operations process these efficiently before feeding into a model.

In [4]:
import numpy as np

# Creating array from a list
list_data = [10, 20, 30, 40]
array_from_list = np.array(list_data)

# Built-in generator arrays
zeros_grid = np.zeros((3, 4))       # 3x4 array filled with zeros
ones_grid = np.ones((2, 3))         # 2x3 array filled with ones
range_array = np.arange(0, 10, 2)   # Sequence from 0 to 8 with step 2
linear_array = np.linspace(0, 1, 5) # 5 evenly spaced points between 0 and 1

print("Array from List:", array_from_list)
print("\n3x4 Zeros Grid:\n", zeros_grid)
print("\n2x3 Ones Grid:\n", ones_grid)
print("\nArange (0 to 10, step 2):", range_array)
print("\nLinspace (0 to 1, 5 values):", linear_array)

Array from List: [10 20 30 40]

3x4 Zeros Grid:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x3 Ones Grid:
 [[1. 1. 1.]
 [1. 1. 1.]]

Arange (0 to 10, step 2): [0 2 4 6 8]

Linspace (0 to 1, 5 values): [0.   0.25 0.5  0.75 1.  ]


---

## 3. NumPy Arrays (ndarray)

### Concept Explanation
The `ndarray` (N-Dimensional Array) is NumPy's main data structure. It is a grid of elements, all of the same data type, indexed by a tuple of non-negative integers.

### Real-world Example
A multi-story parking garage structure where every single space is uniform and assigned a specific floor, row, and spot number.

### Business Example
A logistics company representing inventory levels across warehouse locations, product categories, and aisle shelves using a 3D `ndarray`.

### AI/ML Example
A grayscale image is represented as a 2D `ndarray` where every value represents a pixel intensity between 0 and 255.

In [5]:
import numpy as np

# Creating a 2D ndarray
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D ndarray:\n", matrix)

2D ndarray:
 [[1 2 3]
 [4 5 6]]


---

## 4. Creating Arrays from Lists

### Concept Explanation
You can convert existing Python lists or nested lists directly into NumPy arrays using the `np.array()` function.

### Real-world Example
Converting a written list of daily temperature readings recorded over a week into a structured numerical format.

### Business Example
Converting a list of monthly sales totals exported from a simple tracking system into a NumPy array for mathematical modeling.

### AI/ML Example
Converting raw user feedback ratings stored in a standard list into an array to feed into a sentiment analysis pre-processing pipeline.

In [6]:
import numpy as np

# Creating an array from a list
python_list = [10.5, 20.0, 30.2, 40.8]
numpy_array = np.array(python_list)

print("Array from List:", numpy_array)

Array from List: [10.5 20.  30.2 40.8]


---

## 5. Creating Arrays with `np.zeros`

### Concept Explanation
The `np.zeros()` function creates an array of a specified shape where every element is pre-filled with the floating-point value `0.0`.

### Real-world Example
Preparing a blank sheet of grid paper with all empty cells before starting to fill in field measurements.

### Business Example
Allocating a blank memory table to hold calculated monthly revenue projections before running the calculation loop.

### AI/ML Example
Initializing weight matrices or bias vectors in neural networks to zero before starting model initialization algorithms.

In [7]:
import numpy as np

# Creating a 2x3 grid of zeros
zeros_array = np.zeros((2, 3))
print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


---

## 6. Creating Arrays with `np.ones`

### Concept Explanation
The `np.ones()` function generates an array of a given shape populated entirely with the value `1.0`.

### Real-world Example
Setting up a score board where every participant starts with a base score of 1 point.

### Business Example
Creating a baseline unit matrix where all multiplication factors default to 1 before applying variable business adjustments.

### AI/ML Example
Creating mask matrices filled with ones to preserve specific features during image or text processing pipelines.

In [8]:
import numpy as np

# Creating a 3x3 matrix filled with ones
ones_array = np.ones((3, 3))
print("Ones Array:\n", ones_array)

Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


---

## 7. Creating Arrays with `np.arange`

### Concept Explanation
`np.arange()` generates an array with evenly spaced numerical values within a specified interval by defining a `start`, `stop` (exclusive), and `step` size.

### Real-world Example
Setting up time markers on a stopwatch that ticks every 5 seconds from 0 to 60 seconds.

### Business Example
Generating an array of index sequence numbers corresponding to customer transaction IDs across a fixed batch run.

### AI/ML Example
Creating time-step indices for time-series forecasting models to track regular observation intervals.

In [9]:
import numpy as np

# Create an array from 0 to 20 (exclusive) with a step size of 2
arange_array = np.arange(0, 20, 2)
print("Arange Array:", arange_array)

Arange Array: [ 0  2  4  6  8 10 12 14 16 18]


---

## 8. Creating Arrays with `np.linspace`

### Concept Explanation
`np.linspace()` generates an array with a specified number of evenly spaced points over a defined closed interval `[start, stop]`. Unlike `arange`, you specify the exact total count of numbers rather than the step size.

### Real-world Example
Dividing a 100-meter track into 5 equal check-points.

### Business Example
Generating 10 evenly spaced price levels between a minimum discount price and a maximum retail price for pricing sensitivity testing.

### AI/ML Example
Generating continuous sample points along a curve to plot loss functions or decision boundaries during model training visualization.

In [10]:
import numpy as np

# Create 5 evenly spaced numbers between 0 and 10
linspace_array = np.linspace(0, 10, 5)
print("Linspace Array:", linspace_array)

Linspace Array: [ 0.   2.5  5.   7.5 10. ]


---

## 9. Dimensions (`ndim`)

### Concept Explanation
The `ndim` attribute reveals the total number of axes or dimensions possessed by an `ndarray` (e.g., 1D vector, 2D matrix, 3D tensor).

### Real-world Example
A straight line of numbers is 1-dimensional, a flat page/grid is 2-dimensional, and a cube structure is 3-dimensional.

### Business Example
An analytics script checking `ndim` to verify whether incoming sales data is a simple list (1D) or a table across branches and quarters (2D).

### AI/ML Example
Ensuring an input vector is transformed into a 2D matrix (batch size × features) before feeding it into a Scikit-Learn regression model.

In [11]:
import numpy as np

arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array ndim:", arr_1d.ndim)
print("2D Array ndim:", arr_2d.ndim)

1D Array ndim: 1
2D Array ndim: 2


---

## 10. Shape (`shape`)

### Concept Explanation
The `shape` attribute returns a tuple of integers indicating the size/length of the array along each of its dimensions (axes).

### Real-world Example
A chessboard has a shape of `(8, 8)` representing 8 rows and 8 columns.

### Business Example
Verifying that an imported table has a `(1000, 5)` shape, confirming 1,000 rows of transactions with 5 attribute columns.

### AI/ML Example
Checking the shape of an image array to verify if it meets the `(224, 224, 3)` input standard required by a Convolutional Neural Network (CNN).

In [12]:
import numpy as np

matrix = np.array([[10, 20, 30], [40, 50, 60]])
print("Shape of Matrix:", matrix.shape)  # Output: (rows, columns)

Shape of Matrix: (2, 3)


---

## 11. Size (`size`)

### Concept Explanation
The `size` attribute gives the total count of elements contained within the entire array across all dimensions (equal to the product of the shape values).

### Real-world Example
An egg carton holding 2 rows of 6 eggs has a total size of 12 eggs.

### Business Example
Calculating the total data entries recorded in an array to estimate total memory footprint or data completeness.

### AI/ML Example
Determining the total number of input features in a flattened matrix before passing it into a dense layer.

In [13]:
import numpy as np

grid = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Total Elements (size):", grid.size)

Total Elements (size): 8


---

## 12. Data Types (`dtype`)

### Concept Explanation
The `dtype` attribute indicates the specific data type stored within the homogeneous array (e.g., `int32`, `float64`, `bool`).

### Real-world Example
A signpost displaying room temperatures uses floating-point numbers (`22.5`), while an elevator display showing floor numbers uses integers (`3`).

### Business Example
Ensuring financial amounts are stored as 64-bit floats (`float64`) to preserve precision during currency calculations.

### AI/ML Example
Converting image pixel values from 8-bit integers (`uint8`) to 32-bit floats (`float32`) for numerical scaling and model stability.

In [14]:
import numpy as np

int_arr = np.array([1, 2, 3])
float_arr = np.array([1.0, 2.5, 3.8])

print("Integer Array dtype:", int_arr.dtype)
print("Float Array dtype:", float_arr.dtype)

Integer Array dtype: int64
Float Array dtype: float64


---

## 13. Indexing

### Concept Explanation
Indexing accesses a single element inside an `ndarray` using zero-based coordinate positions.

### Real-world Example
Picking the exact book placed on shelf 2 at position 4.

### Business Example
Extracting the revenue figure for store #3 on day #15 directly from a multidimensional array.

### AI/ML Example
Retrieving the top prediction probability score for a single target class from an output tensor.

In [15]:
import numpy as np

# 1D Indexing
arr = np.array([10, 20, 30, 40])
print("First Element:", arr[0])

# 2D Indexing (row, column)
matrix = np.array([[1, 2], [3, 4]])
print("Element at row 1, column 0:", matrix[1, 0])

First Element: 10
Element at row 1, column 0: 3


---

## 14. Slicing

### Concept Explanation
Slicing extracts a continuous subset from an array using `[start:stop:step]` syntax along any axis without making a new memory copy.

### Real-world Example
Cutting out days 10 through 15 from a monthly wall calendar.

### Business Example
Selecting the first 100 high-value transaction rows from a sorted sales matrix for auditing.

### AI/ML Example
Splitting an input dataset into training and validation sets using range slices.

In [16]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
print("Sliced Array (index 1 to 4):", arr[1:5])

Sliced Array (index 1 to 4): [20 30 40 50]


---

## 15. Reshaping (`reshape`)

### Concept Explanation
`reshape()` changes the shape (dimensions) of an array without altering its underlying element values or total count.

### Real-world Example
Rearranging 12 sodas from a single long line of 12 cans into a 3×4 box layout.

### Business Example
Re-organizing a 1D stream of 365 daily revenue figures into a 52-week 2D matrix structure.

### AI/ML Example
Reshaping a 1D vector of 784 image pixels into a 2D matrix of `(28, 28)` pixels before visualization.

In [17]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6])
reshaped_2d = arr_1d.reshape(2, 3)

print("Reshaped 2x3 Matrix:\n", reshaped_2d)

Reshaped 2x3 Matrix:
 [[1 2 3]
 [4 5 6]]


---

## 16. Flattening (`flatten` vs `ravel`)

### Concept Explanation
Flattening collapses a multi-dimensional array down into a 1D array. `flatten()` creates an independent physical copy, whereas `ravel()` returns a view of the original memory when possible.

### Real-world Example
Unrolling a folded multi-page map into a single flat strip of paper.

### Business Example
Converting a multi-region product matrix into a continuous list for export to a legacy database system.

### AI/ML Example
Flattening a 2D feature map coming out of a convolutional layer before feeding it into a fully connected neural network layer.

In [18]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

flat_copy = matrix.flatten()  # Returns copy
flat_view = matrix.ravel()    # Returns view

print("Flattened Array:", flat_copy)

Flattened Array: [1 2 3 4]


---

## 17. Copy vs View

### Concept Explanation
* **View:** A shallow window sharing the original array's memory location. Changes modify the original array.
* **Copy:** A deep, independent duplicate occupying distinct memory.

### Real-world Example
A **View** is like a shortcut link to a document on your computer. A **Copy** is like duplicating the file onto a USB drive.

### Business Example
Making an independent **Copy** of financial data so exploratory scenarios can be run without changing master data.

### AI/ML Example
Using **Views** when processing massive datasets to conserve GPU/RAM usage without generating unnecessary duplicates.

In [19]:
import numpy as np

original = np.array([10, 20, 30])

view_arr = original.view()
copy_arr = original.copy()

view_arr[0] = 999  # Modifying view affects original

print("Original Array:", original)   # Modified
print("Independent Copy:", copy_arr) # Unchanged

Original Array: [999  20  30]
Independent Copy: [10 20 30]


---

## 18. Broadcasting

### Concept Explanation
Broadcasting automatically expands smaller arrays across larger arrays during arithmetic operations, allowing operations between arrays of different compatible shapes without manual looping.

### Real-world Example
Adding a uniform $5 shipping fee to every item price listed in a catalog shopping cart.

### Business Example
Applying a single tax multiplier scalar directly across a multi-column matrix of store revenues.

### AI/ML Example
Subtracting mean values from feature columns during data normalization and feature scaling pipelines.

In [20]:
import numpy as np

prices = np.array([100, 200, 300])
tax = 1.18  # Single scalar value broadcasted to all elements

final_prices = prices * tax
print("Final Prices with Tax:", final_prices)

Final Prices with Tax: [118. 236. 354.]


---

## 19. Universal Functions (`ufuncs`)

### Concept Explanation
`ufuncs` are optimized functions in NumPy that run fast, element-by-element mathematical, logical, and trigonometric calculations directly written in C.

### Real-world Example
Using a calculator's `sqrt` button to process a whole column of values at once instead of typing each number manually.

### Business Example
Applying logarithm transformations (`np.log`) across skew-distributed sales data to smooth variances for analytical modeling.

### AI/ML Example
Applying activation functions like Sigmoid or ReLU across network layer arrays during neural network forward passes.

In [21]:
import numpy as np

numbers = np.array([1, 4, 9, 16])

print("Square Root ufunc:", np.sqrt(numbers))
print("Exponential ufunc:", np.exp(numbers))

Square Root ufunc: [1. 2. 3. 4.]
Exponential ufunc: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


---

## Minimum 5 Interview Questions with Answers

1. **What is the primary difference between a Python List and a NumPy Array?**  
   * **Answer:** Python lists store pointer references to objects scattered across memory and accept mixed data types. NumPy arrays store uniform data sequentially in contiguous memory blocks, allowing fast vectorized processing.

2. **What happens when you create a NumPy array with mixed data types?**  
   * **Answer:** NumPy automatically performs upcasting (type coercion) to convert all elements into a single unifying data type (e.g., integers and floats become floats; numbers and strings become strings).

3. **What are the rules for NumPy Broadcasting?**  
   * **Answer:** Two dimensions are compatible for broadcasting if they are equal, or if one of the dimensions is equal to 1.

4. **How does `ravel()` differ from `flatten()`?**  
   * **Answer:** `flatten()` always returns a new deep copy with fresh memory allocated, whereas `ravel()` returns a view of the original array whenever possible without copying memory.

5. **How can you check if an array shares memory with another array?**  
   * **Answer:** You can check the `.base` attribute. If `array2.base` refers to `array1`, then `array2` is a view. If `array2.base` is `None`, it owns its memory.

---

## Self Reflection
* **What I Learned:** Learned how NumPy handles array instantiation, metadata properties, memory references (copy vs view), indexing/slicing, vectorization, and broadcasting.
* **Key Takeaway:** Eliminating explicit Python loops using vectorization and `ufuncs` drastically increases computational speed for machine learning workflows.

In [22]:
import numpy as np

numbers = np.array([1, 4, 9, 16])

print("Square Root ufunc:", np.sqrt(numbers))
print("Exponential ufunc:", np.exp(numbers))

Square Root ufunc: [1. 2. 3. 4.]
Exponential ufunc: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


---

## 5 Interview Questions with Answers

1. **What is the primary difference between a Python List and a NumPy Array?**  
   * **Answer:** Python lists store pointer references to objects scattered across memory and accept mixed data types. NumPy arrays store uniform data sequentially in contiguous memory blocks, allowing fast vectorized processing.

2. **What happens when you create a NumPy array with mixed data types?**  
   * **Answer:** NumPy automatically performs upcasting (type coercion) to convert all elements into a single unifying data type (e.g., integers and floats become floats; numbers and strings become strings).

3. **What are the rules for NumPy Broadcasting?**  
   * **Answer:** Two dimensions are compatible for broadcasting if they are equal, or if one of the dimensions is equal to 1.

4. **How does `ravel()` differ from `flatten()`?**  
   * **Answer:** `flatten()` always returns a new deep copy with fresh memory allocated, whereas `ravel()` returns a view of the original array whenever possible without copying memory.

5. **How can you check if an array shares memory with another array?**  
   * **Answer:** You can check the `.base` attribute. If `array2.base` refers to `array1`, then `array2` is a view. If `array2.base` is `None`, it owns its memory.

---

## Self Reflection
* **What I Learned:** Learned how NumPy handles array instantiation, metadata properties, memory references (copy vs view), indexing/slicing, vectorization, and broadcasting.
* **Key Takeaway:** Eliminating explicit Python loops using vectorization and `ufuncs` drastically increases computational speed for machine learning workflows.